name: smart_tourist_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7

  # !! BADAL KELA !! - firebase_messaging chi version downgrade keli, error nusar
  firebase_messaging: ^14.9.4

  # Location, Maps, and Scanner packages
  location: ^6.0.2
  google_maps_flutter: ^2.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Image and media packages
  image_picker: ^1.1.2
  http: ^1.2.1
  mime: ^1.0.5
  crypto: ^3.0.3

  # Other packages
  vibration: ^1.8.4
  flutter_local_notifications: ^17.2.1
  device_preview_plus: ^2.2.7

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true