name: smart_tourist_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

  # !! BADAL KELA !! - firebase_messaging chi version downgrade keli, error nusar
  firebase_messaging: ^16.0.4
  firebase_app_check: ^0.4.1+3
  video_player: ^2.8.6

  # Location, Maps, and Scanner packages
  location: ^8.0.1
  google_maps_flutter: ^2.7.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3

  # Image and media packages
  image_picker: ^1.1.2
  http: ^1.2.1
  mime: ^2.0.0
  crypto: ^3.0.3

  # Other packages
  vibration: ^3.1.4
  flutter_local_notifications: ^19.5.0

  # State management and persistence
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  package_info_plus: ^9.0.0
  ota_update: ^7.1.0
  permission_handler: ^12.0.1
  get: ^4.6.5
  intl: ^0.20.2

  # Rating and feedback
  in_app_review: ^2.0.10
  confetti: ^0.8.0
  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.8
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/videos/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
